language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: package
      install:
        - mvn clean package
    - stage: deploy staging
      install: 
        - sudo apt-get update -qq
        - sudo apt-get install -yq python-pip python-dev ssh
        - sudo pip install ansible
      script: ansible-playbook ansible/playbook.yml -i "../inventory"
    - stage: deploy prod
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -yq python-pip python-dev
        - sudo pip install ansible
      script: ansible-playbook ansible/playbook.yml --extra-vars "target=localhost"
