language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: package
      install:
        - mvn clean package
    - stage: deploy staging
      install: 
        - sudo apt-get update -qq
        - sudo apt-get install -yq python-pip python-dev
        - sudo pip install ansible
      script: ansible-playbook -i "localhost," -c local ansible/playbook.yml
    - stage: deploy prod
      install:
        - sudo apt-get update -qq
