language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: package
      install:
        - mvn clean package
    - stage: deploy staging
      install: 
        - sudo apt-get update -qq
        - sudo apt-get install -yq python-pip python-dev ssh
        - sudo pip install ansible
      script: 
        - sudo ansible-playbook -i ansible/staging/inventory ansible/playbook.yml
        - sudo chmod +x tests/test.sh && ./test.sh 52.47.90.234  
    - stage: deploy prod
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -yq python-pip python-dev
        - sudo pip install ansible
      script: 
        - sudo ansible-playbook -i ansible/production/inventory ansible/playbook.yml
        - sudo chmod +x tests/test.sh && ./test.sh 35.180.39.255  
