before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yq python-pip python-dev
  - sudo pip install ansible

language: java
jdk:
  - oraclejdk8
install:
  - mvn clean package

after_success:
  - echo "coucou"
