language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: package
      install:
        - mvn clean package
    - stage: deploy staging
      install: 
        - sudo apt-get update -qq
        - sudo apt-get install -yq python-pip python-dev ssh
        - sudo pip install ansible
      script: ansible-playbook ansible/playbook.yml --extra-vars "target=ec2-34-227-157-137.compute-1.amazonaws.com" ansible_ssh_private_key_file=/home/travis/build/Nakada78/Xebia-Click-recrutement/xebia.pem ansible_user=ec2-user
    - stage: deploy prod
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -yq python-pip python-dev
        - sudo pip install ansible
      script: ansible-playbook ansible/playbook.yml --extra-vars "target=localhost"
