---
repo_github: https://github.com/Nakada78/Xebia-Click-recrutement.git 
dest_repo_github: /opt/Xebia-code
repo: ppa:chris-lea/redis-server
redis_dependencies:
  - vim
  - wget
  - git
  - unzip
  - software-properties-common
  - openjdk-8-jdk
